spring.application.name=ScreenmatchRevisao
spring.datasource.url=jdbc:postgresql://localhost/alura_series_revisao
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.drive-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update
